#!/usr/bin/env python3
"""Strip a generated factory's look-dev harness so only the model factory ships.

`generate_threejs_factory.py` emits the model factory plus a preview harness — lights,
an environment, a camera framer, a bloom/bokeh composer, orbit controls. The harness is
useful in the skill's own review loop and dead weight in this bundle: it pulls six
`three/examples/jsm` modules into a page that already owns its lighting and its post
chain. Trimming is a packaging decision, not a reconstruction decision, so it runs as a
post-step on regeneration rather than as a hand edit to the artifact.

Usage: trim_lookdev.py <generated.ts>
"""
import re
import sys
from pathlib import Path

DROPPED_IMPORTS = (
    "RoomEnvironment", "EffectComposer", "RenderPass", "BokehPass", "UnrealBloomPass", "OrbitControls",
)
DROPPED_EXPORTS = ("LookDevLights", "Environment", "Camera", "PresentationComposer", "Renderer", "InspectControls")

path = Path(sys.argv[1])
source = path.read_text()

lines = [
    line for line in source.splitlines()
    if not (line.startswith("import {") and any(name in line for name in DROPPED_IMPORTS))
]

# Drop each look-dev export and everything up to the next top-level declaration.
out, skipping = [], False
for line in lines:
    if line.startswith("export function ") and any(line.split("export function ")[1].startswith(f"create{s}") or s in line.split("(")[0] for s in DROPPED_EXPORTS):
        skipping = True
    elif skipping and (line.startswith("export ") or line.startswith("function ") or line.startswith("const ")):
        skipping = False
    if not skipping:
        out.append(line)

trimmed = "\n".join(out).rstrip() + "\n"
trimmed = re.sub(r"\n{3,}", "\n\n", trimmed)

# This project declares `three` as a bare module (app/joi-signal-lab/three.d.ts), so
# `THREE.Mesh` resolves as a value but not as a type — every hand-written module here
# uses `any` in type positions to match. Generated code annotates with real THREE types
# throughout. Rewriting those annotations would be a diff against the generator on every
# regeneration, so the generated file opts out of checking instead, and the spec plus the
# skill's own gates remain what this artifact is verified against.
header = (
    "// @ts-nocheck\n"
    "// Generated by img2threejs from scripts/props/<prop>/spec.json, then trimmed by\n"
    "// scripts/props/trim_lookdev.py. Do not hand-edit: change the spec and regenerate.\n"
    "// Checking is off because `three` is declared as a bare module in this project.\n"
)
trimmed = header + trimmed
path.write_text(trimmed)
print(f"trimmed {path}: {len(source.splitlines())} → {len(trimmed.splitlines())} lines")
